class Locators:
    customer_login_email_field = "//*[@name=\"email\"]"
    customer_login_password_field = "//*[@name=\"password\"]"
    customer_login_sign_in_button = "//*[@type=\"submit\"]"
    customer_home_search_button = "//*[@name='search']"
    customer_sign_up_first_name_field = "//*[@id=\"input-firstname\"]"
    customer_sign_up_last_name_field = "//*[@id=\"input-lastname\"]"
    customer_sign_up_phone_field = "//*[@id=\"input-telephone\"]"
    customer_sign_up_email_field = "//*[@id=\"input-email\"]"
    customer_sign_up_show_password = "//*[@class=\"fa fa-eye-slash\"]"
    customer_sign_up_password_field = "//*[@id=\"input-password\"]"
    customer_sign_up_news_letter_yes = "//*[@id=\"newsletter-yes\"]"
    customer_sign_up_agree_policy = "//*[@id=\"agreee_policy\"]"
    customer_sign_up_submit_button = "//button[text()='GET STARTED']"
